### ISSUE TITLE
仓库里的Dockerfile 文件14行的vendors/ 文件夹不在仓库里

### ISSUE THREAD

**Issue by just3019** [wanrenzhizun/docker-yapi-cli#1]
请教一下  Dockerfile 文件14行的vendors/   目录是需要从yapi 官方下吗？

**Comment by mcxinyu** [comment]
是的，yapi项目没有内置在此仓库中，因为已经打包好在镜像里面了，只需要通过compose或者直接pull即可。

**Comment by wanrenzhizun** [comment]
有个git脚步，构建镜像时回去官方拉去的
